load("myGraph.js");
g = new Graph(9);
g.addEdge(0,1);
g.addEdge(0,3);
g.addEdge(1,2);
g.addEdge(1,3);
g.addEdge(2,4);
g.addEdge(4,6);
g.addEdge(4,7);
g.addEdge(7,5);
g.addEdge(7,8);
g.showGraph();
g.dfs(0);
g.bfs(0);
//var paths = g.pathTo(0,8);
//g.showPath(paths);
